// <auto-generated />
namespace _2.Dönem_2.Sinav_Ayberk_Güven_9061.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image));
        
        string IMigrationMetadata.Id
        {
            get { return "202205180847156_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
