// <auto-generated />
namespace DbSinav1_9061_Ayberk_Güven.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addMigration9061Sinav : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMigration9061Sinav));
        
        string IMigrationMetadata.Id
        {
            get { return "202203231426026_add-Migration 9061Sinav"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
